# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: panServiceNow
# label used for menu selection
label: panhandler-ServiceNow
description: Adds ServiceNow HTTP Provider to PanOS.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Lab in a Box

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: profile_name
    description: Name of Serivce Profile
    default: ServiceNowServerProfile
    type_hint: text
  - name: server_name
    description: Enter a Server name for your Service Now Instance. For SE, check loop page for demo instance.
    default: enter ServiceNow instance here
    type_hint: text
  - name: url
    description: ServiceNow instance URL (without https://, example servicenow.servicenow.com)
    type_hint: text
    default: demo.servicenow.com
  - name: user_name
    description: Enter your web services user name here.
    default: admin
    type_hint: text
  - name: password
    description: Enter your Service Now web services password. Note, this is only used when sent to the NGFW, and should not be stored.
    default: admin
    type_hint: text

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: servicenowsece
    xpath: /config/shared/log-settings/http/entry
    file: servicenow.xml
# ---------------------------------------------------------------------
# end of snippets section
