# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: ServiceNowIncidentSkillet
# label used for menu selection
label: ServiceNowIncidentSkillet
description: Adds ServiceNow HTTP Provider to PanOS of the Security Incident payload type.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Lab in a Box Collection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: profile_name
    description: Name of Service Profile
    default: ServiceNowServerProfile
    type_hint: text
  - name: server_name
    description: Enter a Server name for your Service Now Instance. This is the name in the HTTP Servers section.
    default: enter ServiceNow server name here
    type_hint: text
  - name: url
    description: ServiceNow instance URL (without https://, example servicenow.servicenow.com)
    type_hint: text
    default: demo.servicenow.com
  - name: user_name
    description: Enter your web services user name here.
    default: admin
    type_hint: text
  - name: password
    description: Enter your Service Now web services password. WARNING-This password may be cached. This is a side effect of PanHandler. Make sure this is a Web Services only account.
    default: admin
    type_hint: text

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: servicenow
    xpath: /config/shared/log-settings/http
    file: servicenow.xml
# May not be needed.
#  - name: payload
#    xpath: /config/shared/log-settings/http/entry[@name='{{profile_name}}']/format
#    file: sni.xml
# ---------------------------------------------------------------------
# end of snippets section
